[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/jhagas/ESPSupabase.git
    bblanchon/ArduinoJson
    marcoschwartz/LiquidCrystal_I2C

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_MBEDTLS_CLIENT_CERTIFICATE_VERIFICATION=1